// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EVDAL.Models;

public partial class ChargePoints
{
    [Key]
    [Column("ChargePointID", TypeName = "numeric(18, 0)")]
    public decimal ChargePointId { get; set; }

    [Column("ChargeLocationID", TypeName = "numeric(18, 0)")]
    public decimal ChargeLocationId { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string ChargePointType { get; set; }

    [ForeignKey("ChargeLocationId")]
    [InverseProperty("ChargePoints")]
    public virtual ChargeLocation ChargeLocation { get; set; }

    [InverseProperty("ChargePoint")]
    public virtual ICollection<ChargeLog> ChargeLog { get; set; } = new List<ChargeLog>();

    [InverseProperty("ChargePoint")]
    public virtual ICollection<Qrcodes> Qrcodes { get; set; } = new List<Qrcodes>();
}