// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EVDAL.Models;

public partial class ChargeLocation
{
    [Key]
    [Column("ChargeLocationID", TypeName = "numeric(18, 0)")]
    public decimal ChargeLocationId { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string LocationDesc { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string AddressLine1 { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string AddressLine2 { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string City { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string State { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string Zip { get; set; }

    [Column("ClientID", TypeName = "numeric(18, 0)")]
    public decimal ClientId { get; set; }

    [InverseProperty("ChargeLocation")]
    public virtual ICollection<ChargePoints> ChargePoints { get; set; } = new List<ChargePoints>();

    [ForeignKey("ClientId")]
    [InverseProperty("ChargeLocation")]
    public virtual Client Client { get; set; }
}