// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EVDAL.Models;

public partial class ChargeLog
{
    [Key]
    [Column("ChargeLogID", TypeName = "numeric(18, 0)")]
    public decimal ChargeLogId { get; set; }

    [Column("ChargePointID", TypeName = "numeric(18, 0)")]
    public decimal ChargePointId { get; set; }

    [Column("VehicleID", TypeName = "numeric(18, 0)")]
    public decimal VehicleId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ChargeDate { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ChargeUsage { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime StartTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime EndTime { get; set; }

    [Column(TypeName = "numeric(5, 2)")]
    public decimal Cost { get; set; }

    [Column(TypeName = "numeric(5, 2)")]
    public decimal UnitPrice { get; set; }

    [Column("ElectricChargeID", TypeName = "numeric(18, 0)")]
    public decimal ElectricChargeId { get; set; }

    [ForeignKey("ChargePointId")]
    [InverseProperty("ChargeLog")]
    public virtual ChargePoints ChargePoint { get; set; }

    [ForeignKey("ElectricChargeId")]
    [InverseProperty("ChargeLog")]
    public virtual ElectricCharge ElectricCharge { get; set; }

    [ForeignKey("VehicleId")]
    [InverseProperty("ChargeLog")]
    public virtual Vehicle Vehicle { get; set; }
}