// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EVDAL.Models;

public partial class Client
{
    [Key]
    [Column("ClientID", TypeName = "numeric(18, 0)")]
    public decimal ClientId { get; set; }

    [InverseProperty("Client")]
    public virtual ICollection<ChargeLocation> ChargeLocation { get; set; } = new List<ChargeLocation>();

    [InverseProperty("Client")]
    public virtual ICollection<ClientPrice> ClientPrice { get; set; } = new List<ClientPrice>();
}