// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EVDAL.Models;

public partial class ClientPrice
{
    [Key]
    [Column("ClientPriceID", TypeName = "numeric(18, 0)")]
    public decimal ClientPriceId { get; set; }

    [Column("ClientID", TypeName = "numeric(18, 0)")]
    public decimal ClientId { get; set; }

    [Column("PriceID", TypeName = "numeric(18, 0)")]
    public decimal PriceId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime StartDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime EndDate { get; set; }

    [ForeignKey("ClientId")]
    [InverseProperty("ClientPrice")]
    public virtual Client Client { get; set; }

    [ForeignKey("PriceId")]
    [InverseProperty("ClientPrice")]
    public virtual Pricing Price { get; set; }
}