// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EVDAL.Models;

public partial class Customer
{
    [Key]
    [Column("CustomerID", TypeName = "numeric(18, 0)")]
    public decimal CustomerId { get; set; }

    [StringLength(10)]
    public string FirstName { get; set; }

    [StringLength(10)]
    public string LastName { get; set; }

    [StringLength(10)]
    public string Address1 { get; set; }

    [StringLength(10)]
    public string Address2 { get; set; }

    [StringLength(10)]
    public string City { get; set; }

    [StringLength(10)]
    public string State { get; set; }

    [StringLength(10)]
    public string Zip { get; set; }

    [InverseProperty("Customer")]
    public virtual ICollection<Payments> Payments { get; set; } = new List<Payments>();

    [InverseProperty("Customer")]
    public virtual ICollection<Vehicle> Vehicle { get; set; } = new List<Vehicle>();
}