// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EVDAL.Models;

public partial class ElectricCharge
{
    [Key]
    [Column("ElectricChargeID", TypeName = "numeric(18, 0)")]
    public decimal ElectricChargeId { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string State { get; set; }

    [Column(TypeName = "numeric(8, 2)")]
    public decimal UnitPrice { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime StartDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime EndDate { get; set; }

    [InverseProperty("ElectricCharge")]
    public virtual ICollection<ChargeLog> ChargeLog { get; set; } = new List<ChargeLog>();
}