// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EVDAL.Models;

public partial class Makes
{
    [Key]
    [Column("MakeID", TypeName = "numeric(18, 0)")]
    public decimal MakeId { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string MakeDesc { get; set; }

    [InverseProperty("Make")]
    public virtual ICollection<Vehicle> Vehicle { get; set; } = new List<Vehicle>();
}