// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EVDAL.Models;

public partial class Payments
{
    [Key]
    [Column("PaymentID", TypeName = "numeric(18, 0)")]
    public decimal PaymentId { get; set; }

    [Column("CustomerID", TypeName = "numeric(18, 0)")]
    public decimal CustomerId { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("Payments")]
    public virtual Customer Customer { get; set; }
}