// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EVDAL.Models;

public partial class Pricing
{
    [Key]
    [Column("PriceID", TypeName = "numeric(18, 0)")]
    public decimal PriceId { get; set; }

    [Column(TypeName = "numeric(5, 2)")]
    public decimal PricePerLocation { get; set; }

    [InverseProperty("Price")]
    public virtual ICollection<ClientPrice> ClientPrice { get; set; } = new List<ClientPrice>();
}