// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EVDAL.Models;

[Table("QRCodes")]
public partial class Qrcodes
{
    [Key]
    [Column("QRCodeID", TypeName = "numeric(18, 0)")]
    public decimal QrcodeId { get; set; }

    [Column("ChargePointID", TypeName = "numeric(18, 0)")]
    public decimal ChargePointId { get; set; }

    [Column("QRCode", TypeName = "numeric(18, 0)")]
    public decimal Qrcode { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime StartDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime EndDate { get; set; }

    [ForeignKey("ChargePointId")]
    [InverseProperty("Qrcodes")]
    public virtual ChargePoints ChargePoint { get; set; }
}