// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EVDAL.Models;

public partial class Vehicle
{
    [Key]
    [Column("VehicleID", TypeName = "numeric(18, 0)")]
    public decimal VehicleId { get; set; }

    [Column("MakeID", TypeName = "numeric(18, 0)")]
    public decimal MakeId { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Model { get; set; }

    [Required]
    [Column("emailID")]
    [StringLength(100)]
    [Unicode(false)]
    public string EmailId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateCreated { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateModified { get; set; }

    [Required]
    [Column("CreateID")]
    [StringLength(100)]
    [Unicode(false)]
    public string CreateId { get; set; }

    [Required]
    [Column("ModifyID")]
    [StringLength(100)]
    [Unicode(false)]
    public string ModifyId { get; set; }

    [Column("CustomerID", TypeName = "numeric(18, 0)")]
    public decimal CustomerId { get; set; }

    [InverseProperty("Vehicle")]
    public virtual ICollection<ChargeLog> ChargeLog { get; set; } = new List<ChargeLog>();

    [ForeignKey("CustomerId")]
    [InverseProperty("Vehicle")]
    public virtual Customer Customer { get; set; }

    [ForeignKey("MakeId")]
    [InverseProperty("Vehicle")]
    public virtual Makes Make { get; set; }
}